version: '3.9'

services:
  flask:
    image: yhyaa79/ai-talk:latest        #
    container_name: ai_talk_flask
    restart: unless-stopped
    volumes:
      - ./AI_talk/rate_limits.json:/app/rate_limits.json
      - ./AI_talk/static:/app/static:ro
    expose:
      - "8090"
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:alpine
    container_name: ai_talk_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./AI_talk/static:/app/static:ro
      - certbot-webroot:/var/www/html
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - flask

volumes:
  certbot-webroot:
  certbot-certs: